massive_homework/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html")),
    path("showcase/", include("showcase_app.urls")),
    path(
        "user/",
        include("user_app.urls"),
    ),
    path(
        "user/",
        include("django.contrib.auth.urls"),
    ),
]


if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

showcase_app/urls.py
from django.urls import path

from .views import (
    ProductListView,
    ProductCreateView,
    ProductDetailView,
    ProductUpdateView,
    ProductDeleteView,
    QuestionDetailView,
    QuestionDeleteView,
    QuestionListView,
    AnswerDeleteView,
)


app_name = "showcase_app"

urlpatterns = [
    path("products/", ProductListView.as_view(), name="index"),
    path("product/<int:pk>/", ProductDetailView.as_view(), name="product"),
    path("product/create/", ProductCreateView.as_view(), name="create-product"),
    path(
        "product/<int:pk>/update/", ProductUpdateView.as_view(), name="update-product"
    ),
    path(
        "product/<int:pk>/delete/", ProductDeleteView.as_view(), name="delete-product"
    ),
    path("question/<int:pk>/", QuestionDetailView.as_view(), name="question"),
    path(
        "question/<int:pk>/delete/",
        QuestionDeleteView.as_view(),
        name="delete-question",
    ),
    path(
        "answer/<int:pk>/delete/",
        AnswerDeleteView.as_view(),
        name="delete-answer",
    ),
    path(
        "product/<int:pk>/questions/", QuestionListView.as_view(), name="question-list"
    ),
]

user_app/urls.py
from django.urls import path, include
from .views import (
    register,
    user_login,
    edit,
    edit_user,
    dashboard,
    UserDetailView,
)

app_name = "user_app"


urlpatterns = [
    # post views
    path("dashboard/", dashboard, name="dashboard"),
    path(
        "<int:pk>/",
        UserDetailView.as_view(template_name="user_app/user_detail.html"),
        name="userprofile",
    ),
    path("login/", user_login, name="login"),
    path("register/", register, name="register"),
    path("edit/", edit, name="edit"),
    path("edit/<int:pk>/", edit_user, name="edit-user"),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}
    Base
  {% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

</head>
<body>
<nav class="mb-2 px-3 navbar navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'showcase_app:index' %}">Витрина</a>

  <div>
  {% if request.user.is_staff %}
  <a href="{% url 'admin:index' %}">Админка</a>
  {% endif %}
    {% if user.is_authenticated %}
      <a href="{% url 'user_app:dashboard' %}">{{ request.user.username }}</a>
      <a href="{% url 'logout' %}">Выход</a>
    {% else %}
      <a
        class="btn btn-outline-primary"
        href="{% url 'login' %}">
        Login
      </a>
    {% endif %}
  </div>
</nav>

<div class="container">
  {% block body %}

  {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
  Заглавная страница
{% endblock %}

{% block body %}

  <h1>Hello!</h1>

  <div>
    <p>Ссылки:</p>
    <ul>
      <li>
        <a href="{% url 'showcase_app:index' %}">Витрина</a>
      </li>
      <li>
        <a href="{% url 'login' %}">Логин</a>
      </li>
    </ul>
  </div>
{% endblock %}